travis:
  secure:
    BINSTAR_TOKEN: qK8qTbWa+0Py8+PZgj7gjUl57u5VSLvv3SvZh2eSFxLwlZx2sAcbQ1rEg7RjA6HPWQQCAfwlYGhtsvOjbdnH6GrJUAdqoUrE9die7F4hsDfpa7y0XlHMqLrlRNtGa1CC7FEBqynqt6pEFV4eyBrDEXGZCqE5MftBwT0sjFaVd6W64G0WogPvJ+2UoOs9VUr6opo/Ln3wX8a7tZpSw7b2HXG2Q6AOelqVzLrB4tvcTIvXbBnNrcfHEwce4WNoTJzZmCuJsZE093oPdwuO6prqSrMqPM7PtDgK5QtR48vib8ldOJjly627p52MDgWZC4gWtor9yvIoP43WlzNkSb3UYnOsKpXrmqDmTVf3CV+QrdjWc9XNKTkXoN6v7TTHA3GlLtfjlQZ0H4dsHCR7OD2DIPxG9rGJSGGXA9GfN56ze2PJV/H1GYODjs/y97yl8JsMwiKMzFwl777GJReJKHTcRsFcCdYAT2K6ZCVCMDWDU8bdkPlVf8T7mhGA3SSegc8q1nsSeeeNrg1yNZqPAg81kCapUAi2D01Bx+dxKU31GpM4WBTFpMI+hcdVXS322plcmFPztRTwhBjdqqR78XkfydAijYWhcXWtxs5Ul02JMrseD3rg+kbW7Gq/3taWcQBoJygK6rV1l767EvFdW8pPonq1C4q7p44XCZtShLKlmoE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
